#!/bin/bash
# simple wrapper 
num=$(echo $1 | awk -F. '{print $NF}')
qsubfile=kalman.$num.qsub
echo setting up $num from work dir $PWD
echo "#!/bin/bash"                                                              >  $qsubfile
echo "#$ -A UTMDACC-DIP"                                                        >> $qsubfile
echo "#$ -pe 1way 16"                                                           >> $qsubfile
echo "#$ -N kalman.$num"                                                        >> $qsubfile
echo "#$ -j y"                                                                  >> $qsubfile
echo "#$ -o \$JOB_NAME.log\$JOB_ID"                                             >> $qsubfile
echo "#$ -q normal "                                                            >> $qsubfile
echo "#$ -l h_rt=02:00:00 "                                                     >> $qsubfile
echo "#$ -cwd "                                                                 >> $qsubfile
echo "#$ -V"                                                                    >> $qsubfile
echo "set -x # Echo commands, use set echo with csh"                            >> $qsubfile
echo "echo \$PE_HOSTFILE |xargs cat"                                             >> $qsubfile
echo "ibrun -n 1 -o 0 python $PWD/../kalmanFilter.py" $1 $2 >> $qsubfile
echo 0.0 > $2
#qsub $qsubfile
# sleep until file available
#while [ ! -e "$2" ]
#do
#  echo waiting for $2 
#  sleep 5
#done
